apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: httpd-container
          image: 192.168.10.14/httpd:latest
          ports:
            - containerPort: 8082  # Use a different port number, e.g., 8082
        - name: nginx-container
          image: 192.168.10.14/nginx:latest
          ports:
            - containerPort: 8083  # Use a different port number, e.g., 8083
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082  # Use the port number of httpd-container
